name: "MeshCentral Agent"
version: "1.0.13"
slug: "meshcentral_agent"
description: "MeshCentral Agent to connect to a server."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
map:
  - ssl:rw
options:
  mesh_server_url: ""
  mesh_install_token: ""
  hass_webhook_id: ""
schema:
  mesh_server_url: str
  mesh_install_token: str
  hass_webhook_id: str?
host_network: true
host_pid: true
full_access: true
host_dbus: true
