# config.yaml
name: "MeshCentral Agent"
version: "1.0.2"
slug: "meshcentral_agent"
description: "MeshCentral Agent to connect to a server."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
map:
  - ssl:rw
options:
  mesh_server_url: ""
  mesh_install_token: ""
  hass_webhook_id: ""
schema:
  mesh_server_url: str
  mesh_install_token: str
  hass_webhook_id:
    str?:
      help: "The webhook ID to trigger a host reboot from the add-on. Create a Home Assistant automation with a Webhook trigger and this ID, and call the 'hassio.host_reboot' service as an action."
